import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import Navbar from "../components/Navbar";


const inter = Inter( { subsets: [ "latin" ] } );

export const metadata: Metadata = {
  title: "Quest",
  description: "Generated by create next app",
};

export default function leaderboardLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <>
      <div>
        <Navbar />
        { children }
        </div>

    </>
  );
}
