import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
// import { Provider } from "react-redux";
import { store } from "../redux/store";
import { Providers } from "./provider";

const inter = Inter( { subsets: [ "latin" ] } );

export const metadata: Metadata = {
  title: "Quest",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en">
      <body>
        <Providers>{ children }</Providers>
        <Footer/>
      </body>
    </html>
  );
}
