"use client"
import type { Metadata } from "next";
import { useProtectedRoute } from "@/utils/privateRoute";
import { BallTriangle } from "react-loader-spinner";
import { useEffect, useState } from "react";



// export const metadata: Metadata = {
//   title: "Cluster Protocol",
//   description: "Generated by create next app",
// };

export default function KolPLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )

{
    const [isClient, setIsClient] = useState(false)
    const { isLoading, hasAccess } = useProtectedRoute("kol");

    useEffect(() => {
      setIsClient(true)
    }, [])
    if (!isClient) return (
        <div className="flex justify-center h-screen items-center">
        <BallTriangle/>
        </div>
      );
    if (isLoading) {
    
     return   <div className="flex justify-center h-screen items-center">
        <BallTriangle/>
        </div>
        }
        
        if (hasAccess) {
            // Render children if the role matches
            return <>{children}</>;
        }
        
}
