"use client";
import type { Metadata } from "next";
import { useProtectedRoute } from "@/utils/privateRoute";
import { BallTriangle } from "react-loader-spinner";



// export const metadata: Metadata = {
//   title: "Cluster Protocol",
//   description: "Generated by create next app",
// };

export default function KolLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  const { isLoading, hasAccess } = useProtectedRoute( "kol" );
  if ( isLoading )
  {
    <div className="flex justify-center h-screen items-center">
      <BallTriangle />
    </div>;
  }
  if ( hasAccess )
  {
    // Render children if the role matches
    return <>{ children }</>;
  }

}
